"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { AppPage } from "@/components/app-shell";
import { supabase } from "@/lib/supabase";
type Receipt={amount:number;payment_method:string;received_at:string;customer:{name:string}|{name:string}[]|null;project:{subject:string;session_type:string|null}|{subject:string;session_type:string|null}[]|null;artist:{display_name:string}|{display_name:string}[]|null};
function one<T>(v:T|T[]|null){return Array.isArray(v)?v[0]??null:v} function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v)}
export default function DepositReceiptPage(){const{id}=useParams<{id:string}>();const[deposit,setDeposit]=useState<Receipt|null>(null);const[error,setError]=useState("");useEffect(()=>{void supabase.from("deposits").select("amount, payment_method, received_at, customer:customers(name), project:projects(subject, session_type), artist:staff(display_name)").eq("id",id).single().then(({data,error:e})=>{if(e)setError(e.message);else setDeposit(data as unknown as Receipt)})},[id]);const customer=one(deposit?.customer??null),project=one(deposit?.project??null),artist=one(deposit?.artist??null),isCash=deposit?.payment_method==="cash";return <AppPage eyebrow="Projects" title="Deposit receipt"><style jsx global>{`@media screen{.deposit-receipt{width:64mm;padding:4mm;font-size:3.4mm}}@media print{@page{size:72mm 150mm;margin:4mm}body *{visibility:hidden!important}.deposit-receipt,.deposit-receipt *{visibility:visible!important}.deposit-receipt{position:absolute;top:0;left:0;width:64mm!important;padding:4mm!important;border:.7mm solid #000!important;box-shadow:none!important}aside,header,nav,.print-actions{display:none!important}}`}</style><section className="deposit-receipt mx-auto border-2 border-black bg-white shadow-sm">{error?<p>{error}</p>:deposit?<><p className="text-xs font-black uppercase tracking-[.1em]">Deposit received by</p><h2 className="mt-2 text-4xl font-black">{artist?.display_name??"-"}</h2><p className="mt-2 text-xs">{new Date(deposit.received_at).toLocaleString("en-US")}</p><div className="mt-4 border-t-2 border-dashed border-black pt-3"><p className="text-xs uppercase">Client</p><p className="text-xl font-black">{customer?.name??"-"}</p></div><div className="mt-3 border-t border-dashed border-black pt-3"><p className="text-xs uppercase">Project</p><p className="font-bold">{project?.subject??"-"}</p><p className="text-xs">{project?.session_type??"Multiple Session"}</p></div><div className="mt-4 grid grid-cols-[1fr_auto] border-t-2 border-black pt-3 text-lg"><span>{isCash?"Cash deposit":"App deposit"}</span><strong>{money(Number(deposit.amount))}</strong></div><div className="mt-3 grid grid-cols-[1fr_auto] border-t-2 border-black pt-3 text-xl"><span>Total to drop</span><strong>{money(isCash?Number(deposit.amount):0)}</strong></div>{!isCash?<p className="mt-2 text-xs">Artist received and holds this App deposit.</p>:null}</>:<p>Loading...</p>}</section>{deposit?<div className="print-actions mx-auto mt-4 flex justify-center gap-2"><button className="h-10 rounded bg-black px-4 text-sm font-bold text-white" onClick={()=>window.print()}>Print</button><Link className="inline-flex h-10 items-center rounded border px-4 text-sm font-bold" href="/projects">Back to projects</Link></div>:null}</AppPage>}
