-- Update existing operations email templates to the Oyabun branded HTML style.
-- Run after docs/operations_email_templates_migration.sql if rows already exist.

with branded_templates(template_key, subject, body_html, enabled, test_mode) as (
  values
    (
      'request_auto_reply',
      'We received your tattoo request',
      $$<table style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;background:#ffffff;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#333333;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center"><table style="border-collapse:collapse;border-spacing:0;background:#ffffff;width:600px;max-width:100%;" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td style="padding:20px 20px 0;" align="center"><img width="220" style="display:block;border:0;max-width:220px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"></td></tr><tr><td style="padding:20px 20px 25px;" align="center"><table style="border-collapse:separate;border-spacing:0;border:3px solid #ffc600;border-radius:20px;width:100%;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td style="height:26px;">&nbsp;</td></tr><tr><td style="padding:0 38px;" align="center"><h1 style="margin:0;font-size:28px;line-height:1.25;color:#333333;font-weight:700;">We received your tattoo request</h1></td></tr><tr><td style="padding:12px 38px 0;" align="center"><p style="margin:0;font-size:18px;line-height:1.45;color:#333333;"><em>Thank you for trusting Oyabun Tattoo with your idea.</em></p></td></tr><tr><td style="padding:24px 38px 0;text-align:left;font-size:16px;line-height:1.55;color:#333333;"><p style="margin:0 0 14px;">Hi {{customerName}},</p><p style="margin:0 0 14px;">Thanks for reaching out. We received your tattoo request and our team will review it shortly.</p><p style="margin:0 0 14px;"><strong>We usually reply within 2 business days.</strong> If we need more details, we will contact you by email.</p><p style="margin:0;"><strong>Artist preference:</strong> {{artistPreference}}</p></td></tr><tr><td style="height:30px;">&nbsp;</td></tr></tbody></table></td></tr><tr><td style="padding:14px 20px 18px;background:#ffc600;" align="center"><img width="170" style="display:block;border:0;max-width:170px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"><p style="margin:12px 0 0;font-size:14px;line-height:1.5;color:#111111;">8199 Clairemont Mesa Blvd., Suite L<br>San Diego, CA 92111<br>(858) 384-6099<br>contact@oyabuntattoo.com</p><p style="margin:12px 0 0;"><a href="https://www.instagram.com/yushitattoo/"><img height="32" style="display:inline-block;border:0;" alt="Instagram" src="https://jviaxe.stripocdn.email/content/assets/img/social-icons/circle-black/instagram-circle-black.png"></a></p></td></tr><tr><td style="padding:10px 20px 18px;" align="center"><p style="margin:0;font-size:10px;line-height:1.4;color:#333333;"><a style="color:#333333;" href="https://www.oyabuntattoo.com">WWW.OYABUNTATTOO.COM</a> @ OYABUN TATTOO</p></td></tr></tbody></table></td></tr></tbody></table>$$,
      false,
      true
    ),
    (
      'appointment_confirmation_1',
      'Appointment confirmed: {{projectName}}',
      $$<table style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;background:#ffffff;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#333333;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center"><table style="border-collapse:collapse;border-spacing:0;background:#ffffff;width:600px;max-width:100%;" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td style="padding:20px 20px 0;" align="center"><img width="220" style="display:block;border:0;max-width:220px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"></td></tr><tr><td style="padding:20px 20px 25px;" align="center"><table style="border-collapse:separate;border-spacing:0;border:3px solid #ffc600;border-radius:20px;width:100%;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td style="height:26px;">&nbsp;</td></tr><tr><td style="padding:0 38px;" align="center"><h1 style="margin:0;font-size:28px;line-height:1.25;color:#333333;font-weight:700;">Your appointment is confirmed</h1></td></tr><tr><td style="padding:12px 38px 0;" align="center"><p style="margin:0;font-size:18px;line-height:1.45;color:#333333;"><em>We are excited to welcome you to Oyabun Tattoo.</em></p></td></tr><tr><td style="padding:24px 38px 0;text-align:left;font-size:16px;line-height:1.55;color:#333333;"><p style="margin:0 0 14px;">Hi {{customerName}},</p><p style="margin:0 0 14px;">Your appointment has been confirmed. Please review the details below before your visit.</p><p style="margin:0 0 14px;"><strong>Project:</strong> {{projectName}}<br><strong>Artist:</strong> {{artistName}}<br><strong>Appointment:</strong> {{appointmentTime}}</p><p style="margin:0;">Please eat beforehand, hydrate, avoid alcohol, and wear comfortable clothing that gives access to the tattoo placement.</p></td></tr><tr><td style="height:30px;">&nbsp;</td></tr></tbody></table></td></tr><tr><td style="padding:14px 20px 18px;background:#ffc600;" align="center"><img width="170" style="display:block;border:0;max-width:170px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"><p style="margin:12px 0 0;font-size:14px;line-height:1.5;color:#111111;">8199 Clairemont Mesa Blvd., Suite L<br>San Diego, CA 92111<br>(858) 384-6099<br>contact@oyabuntattoo.com</p></td></tr></tbody></table></td></tr></tbody></table>$$,
      true,
      false
    ),
    (
      'appointment_confirmation_2',
      'Next appointment confirmed: {{projectName}}',
      $$<table style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;background:#ffffff;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#333333;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center"><table style="border-collapse:collapse;border-spacing:0;background:#ffffff;width:600px;max-width:100%;" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td style="padding:20px 20px 0;" align="center"><img width="220" style="display:block;border:0;max-width:220px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"></td></tr><tr><td style="padding:20px 20px 25px;" align="center"><table style="border-collapse:separate;border-spacing:0;border:3px solid #ffc600;border-radius:20px;width:100%;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td style="height:26px;">&nbsp;</td></tr><tr><td style="padding:0 38px;" align="center"><h1 style="margin:0;font-size:28px;line-height:1.25;color:#333333;font-weight:700;">Your next appointment is confirmed</h1></td></tr><tr><td style="padding:12px 38px 0;" align="center"><p style="margin:0;font-size:18px;line-height:1.45;color:#333333;"><em>Your project is moving forward.</em></p></td></tr><tr><td style="padding:24px 38px 0;text-align:left;font-size:16px;line-height:1.55;color:#333333;"><p style="margin:0 0 14px;">Hi {{customerName}},</p><p style="margin:0 0 14px;">Your next appointment has been confirmed.</p><p style="margin:0 0 14px;"><strong>Project:</strong> {{projectName}}<br><strong>Artist:</strong> {{artistName}}<br><strong>Appointment:</strong> {{appointmentTime}}</p><p style="margin:0;">Please continue following your artist's preparation and aftercare guidance between sessions.</p></td></tr><tr><td style="height:30px;">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>$$,
      true,
      false
    ),
    (
      'appointment_reschedule',
      'Appointment rescheduled: {{projectName}}',
      $$<table style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;background:#ffffff;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#333333;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center"><table style="border-collapse:collapse;border-spacing:0;background:#ffffff;width:600px;max-width:100%;" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td style="padding:20px 20px 0;" align="center"><img width="220" style="display:block;border:0;max-width:220px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"></td></tr><tr><td style="padding:20px 20px 25px;" align="center"><table style="border-collapse:separate;border-spacing:0;border:3px solid #ffc600;border-radius:20px;width:100%;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td style="height:26px;">&nbsp;</td></tr><tr><td style="padding:0 38px;" align="center"><h1 style="margin:0;font-size:28px;line-height:1.25;color:#333333;font-weight:700;">Your appointment has been rescheduled</h1></td></tr><tr><td style="padding:12px 38px 0;" align="center"><p style="margin:0;font-size:18px;line-height:1.45;color:#333333;"><em>Please review the updated appointment time.</em></p></td></tr><tr><td style="padding:24px 38px 0;text-align:left;font-size:16px;line-height:1.55;color:#333333;"><p style="margin:0 0 14px;">Hi {{customerName}},</p><p style="margin:0 0 14px;">Your tattoo appointment has been rescheduled.</p><p style="margin:0;"><strong>Project:</strong> {{projectName}}<br><strong>Artist:</strong> {{artistName}}<br><strong>Previous appointment:</strong> {{oldAppointmentTime}}<br><strong>New appointment:</strong> {{newAppointmentTime}}</p></td></tr><tr><td style="height:30px;">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>$$,
      true,
      false
    ),
    (
      'appointment_cancellation',
      'Appointment cancelled: {{projectName}}',
      $$<table style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;background:#ffffff;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#333333;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center"><table style="border-collapse:collapse;border-spacing:0;background:#ffffff;width:600px;max-width:100%;" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td style="padding:20px 20px 0;" align="center"><img width="220" style="display:block;border:0;max-width:220px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"></td></tr><tr><td style="padding:20px 20px 25px;" align="center"><table style="border-collapse:separate;border-spacing:0;border:3px solid #ffc600;border-radius:20px;width:100%;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td style="height:26px;">&nbsp;</td></tr><tr><td style="padding:0 38px;" align="center"><h1 style="margin:0;font-size:28px;line-height:1.25;color:#333333;font-weight:700;">Your appointment has been cancelled</h1></td></tr><tr><td style="padding:12px 38px 0;" align="center"><p style="margin:0;font-size:18px;line-height:1.45;color:#333333;"><em>Reply to this email if you have questions or need to reschedule.</em></p></td></tr><tr><td style="padding:24px 38px 0;text-align:left;font-size:16px;line-height:1.55;color:#333333;"><p style="margin:0 0 14px;">Hi {{customerName}},</p><p style="margin:0 0 14px;">Your tattoo appointment has been cancelled.</p><p style="margin:0;"><strong>Project:</strong> {{projectName}}<br><strong>Artist:</strong> {{artistName}}<br><strong>Original appointment:</strong> {{appointmentTime}}</p></td></tr><tr><td style="height:30px;">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>$$,
      true,
      false
    ),
    (
      'appointment_reminder',
      'Appointment reminder: {{projectName}}',
      $$<table style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;background:#ffffff;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#333333;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td align="center"><table style="border-collapse:collapse;border-spacing:0;background:#ffffff;width:600px;max-width:100%;" cellpadding="0" cellspacing="0" width="600"><tbody><tr><td style="padding:20px 20px 0;" align="center"><img width="220" style="display:block;border:0;max-width:220px;width:100%;height:auto;" alt="Oyabun Tattoo" src="https://jviaxe.stripocdn.email/content/guids/CABINET_6a3bfa96617ed85bcc5a755c7e8d8864/images/logo_trans.png"></td></tr><tr><td style="padding:20px 20px 25px;" align="center"><table style="border-collapse:separate;border-spacing:0;border:3px solid #ffc600;border-radius:20px;width:100%;" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td style="height:26px;">&nbsp;</td></tr><tr><td style="padding:0 38px;" align="center"><h1 style="margin:0;font-size:28px;line-height:1.25;color:#333333;font-weight:700;">Appointment reminder</h1></td></tr><tr><td style="padding:12px 38px 0;" align="center"><p style="margin:0;font-size:18px;line-height:1.45;color:#333333;"><em>Your tattoo appointment is coming up.</em></p></td></tr><tr><td style="padding:24px 38px 0;text-align:left;font-size:16px;line-height:1.55;color:#333333;"><p style="margin:0 0 14px;">Hi {{customerName}},</p><p style="margin:0 0 14px;">This is a reminder for your tattoo appointment tomorrow.</p><p style="margin:0 0 14px;"><strong>Project:</strong> {{projectName}}<br><strong>Artist:</strong> {{artistName}}<br><strong>Appointment:</strong> {{appointmentTime}}</p><p style="margin:0;">Please eat beforehand, hydrate, and arrive prepared for your session.</p></td></tr><tr><td style="height:30px;">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>$$,
      true,
      false
    )
)
insert into public.operations_email_templates
  (template_key, subject, body_html, enabled, test_mode, updated_at)
select template_key, subject, body_html, enabled, test_mode, now()
from branded_templates
on conflict (template_key) do update
set subject = excluded.subject,
    body_html = excluded.body_html,
    enabled = excluded.enabled,
    test_mode = excluded.test_mode,
    updated_at = now();

